version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=200'
    networks:
      pgnet:
        ipv4_address: 172.31.250.10
    restart: unless-stopped

volumes:
  pg_data:

networks:
  pgnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.250.0/26
          gateway: 172.31.250.1
